import uuid
from pathlib import Path
from typing import Any
from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.agents.middleware import (
    HumanInTheLoopMiddleware,
    ModelCallLimitMiddleware,
)
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.types import Command
from langchain_core.runnables import RunnableConfig
from tools.getskill import get_skill
from tools.confluence import get_confluence_page, update_confluence_page
from tools.component_resolver import resolve_components
from tools.jira import (
    create_jira_tickets,
    validate_jira_structure,
)

load_dotenv()

SYSTEM_PROMPT = """
You are a Delivery Engagement Assistant.
            Help Delivery Leads create IT component engagements.
            according to the business skill provided to you.
            
            You have access to specialized skills through the get_skill
tool.

When a user request requires specialized instructions:

1. Identify the required skill.
2. Call get_skill to load it.
3. Follow the loaded skill instructions.
4. Use the appropriate tools.
5. Never invent missing information.
"""
class Agent:

    def __init__(self):
        self.agent = self._build_agent()

        self.thread_id: str | None = None

        self.is_interrupted: bool = False
        self.interrupt_details: Any = None

        # Text generated by the LLM
        self.output_messages: list[str] = []

        # Last LangGraph update
        self.last_update: Any = None
        self.isCompleted: bool = False

    # ------------------------------------------------------------------
    # Build agent
    # ------------------------------------------------------------------
    def get_checkpointer(self):
        """
        POC checkpointer.

        This is intentionally isolated so that we can later
        replace InMemorySaver with a database-backed solution.
        """
        return InMemorySaver()

    def _build_agent(self):

        model = ChatGoogleGenerativeAI(
            model="gemini-3.7-flash",
            temperature=1.0,
        )

        checkpointer = self.get_checkpointer()

        human_in_loop = HumanInTheLoopMiddleware(
            interrupt_on={
                "create_jira_tickets": {
                    "allowed_decisions": [
                        "approve",
                        "reject",
                    ],
                    "description": (
                        "The agent is requesting approval to create "
                        "all proposed Jira tickets in this batch. "
                        "Please review the complete batch and "
                        "approve or reject."
                    ),
                }
            }
        )

        model_call_limit = ModelCallLimitMiddleware(
            run_limit=10,
            exit_behavior="end",
        )

        checkpointer = checkpointer

        tools = [
            get_confluence_page,
            resolve_components,
            validate_jira_structure,
            create_jira_tickets,
            update_confluence_page,
            get_skill,
        ]

        return create_agent(
            model=model,
            tools=tools,
            system_prompt=SYSTEM_PROMPT,
            middleware=[
                human_in_loop,
                model_call_limit,
            ],
            checkpointer=checkpointer,
        )

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------

    def run(
        self,
        confluence_url: str,
        pi_quarter: str,
        navigator_id: str,
    ) -> None:

        self.thread_id = str(uuid.uuid4())

        self._reset_state()

        prompt = self._build_prompt(
            confluence_url,
            pi_quarter,
            navigator_id,
        )

        payload =  {
                        "messages": [
                            {
                                "role": "user",
                                "content": prompt,
                            }
                        ]
                    }

        self._advance(payload)

        
       

        # --------------------------------------------------------------
        # IMPORTANT:
        # After streaming messages, inspect the graph state for HITL.
        # --------------------------------------------------------------

        #self._refresh_interrupt_state(config)

    # ------------------------------------------------------------------
    # Resume
    # ------------------------------------------------------------------

    def resume(self, decision: str) -> None:

        if decision not in {"approve", "reject"}:
            raise ValueError(
                "Decision must be 'approve' or 'reject'."
            )

        if self.thread_id is None:
            raise RuntimeError(
                "There is no active agent thread."
            )

        self.is_interrupted = False
        self.interrupt_details = None

        payload =  Command(
                        resume={
                            "decisions": [
                                {
                                    "type": decision,
                                }
                            ]
                        }
                    )

        self._advance(payload)
        #self._refresh_interrupt_state(config)

    # ------------------------------------------------------------------
    # Process LLM streaming message
    # ------------------------------------------------------------------
    def _advance(self, payload:Any) -> None:
        result = None
        if self.thread_id is None:
            raise RuntimeError(
                "There is no active agent thread."
            )

        config: RunnableConfig = {
            "configurable": {
                "thread_id": self.thread_id,
            }
        }
        
        for message_chunk in self.agent.stream(
            payload,
            config=config,
            stream_mode="values",
        ):

            if message_chunk is None:
                    continue

            result = message_chunk

        if result is None:
            raise RuntimeError(
                "Agent did not return a result."
            )

        # Check for an interrupt.
        if isinstance(result, dict) and "__interrupt__" in result:
            interrupts = result["__interrupt__"]

            if not interrupts:
                raise RuntimeError(
                        f"Worker returned an empty interrupt list: {result}"
                    )

            actions = interrupts[0].value.get("action_requests", [])
            self.is_interrupted = True
            self.interrupt_details = [req["args"] for req in actions if "args" in req]
            self.isCompleted = False
            return
            #self.interrupt_details = actions

        messages = result.get("messages") if isinstance(result, dict) else None

        if not messages:
            raise RuntimeError(
                f"Agent returned no messages: {result}"
            )

        reply = messages[-1].content
        self.output_messages = reply
        self.isCompleted = True

    def _process_message_chunk(
        self,
        message_chunk: Any,
    ) -> None:

        content = getattr(
            message_chunk,
            "content",
            None,
        )

        if not content:
            return

        # Content can sometimes be a list of content blocks.
        if isinstance(content, str):

            self.output_messages.append(content)

        elif isinstance(content, list):

            for block in content:

                if isinstance(block, str):
                    self.output_messages.append(block)

                elif isinstance(block, dict):

                    text = block.get("text")

                    if text:
                        self.output_messages.append(text)

    # ------------------------------------------------------------------
    # Check HITL state
    # ------------------------------------------------------------------

    def _refresh_interrupt_state(
        self,
        config,
    ) -> None:

        state = self.agent.get_state(config)

        interrupts = getattr(
            state,
            "interrupts",
            None,
        )

        if interrupts:
            self.is_interrupted = True
            self.interrupt_details = interrupts
        else:
            self.is_interrupted = False
            self.interrupt_details = None

    # ------------------------------------------------------------------
    # Prompt
    # ------------------------------------------------------------------

    def _build_prompt(
        self,
        confluence_url: str,
        pi_quarter: str,
        navigator_id: str,
    ) -> str:

        return f"""
Read the Confluence Engagement and Dependency page.

Confluence URL:
{confluence_url}

PI Planning Quarter:
{pi_quarter}

Navigator ID:
{navigator_id}

Create Jira engagement ticket proposals for ALL impacted
IT components found on the page.

Follow the capability-engagement skill instructions.

"""

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------
    def reset_agent(self) -> None:
        self.thread_id = None
        self._reset_state()

    def _reset_state(self) -> None:

        self.is_interrupted = False
        self.interrupt_details = None
        self.output_messages = []
        self.last_update = None
        self.isCompleted = False

    @property
    def has_active_thread(self) -> bool:
        return self.thread_id is not None

    @property
    def output_text(self) -> str:
        return "".join(self.output_messages)